// user actions
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const REMOVE_TRANSACTION_SUCCESS = 'REMOVE_TRANSACTION_SUCCESS';

// product actions
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';

//ui actions
export const VIEW_LOADED = 'VIEW_LOADED';
export const START_VIEW_LOADING = 'START_VIEW_LOADING';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';

// admin actions
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const TOGGLE_PROFILE_MENU = 'TOGGLE_PROFILE_MENU';
