export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const ADD_PRODUCT_TO_BASKET_SUCCESS = 'ADD_PRODUCT_TO_BASKET_SUCCESS';
